---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs/_posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs
  label: Pages
  create: documents
  match: "*.md"
  templates:
  - page
upload_dir: docs/.vuepress/public/assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: docs/.vuepress/public
  install_dependencies_command: yarn
  preview_docker_image: node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
